const data = [
  { hex: '#f0f8ff', name: 'Alice Blue' },
  { hex: '#faebd7', name: 'Antique White' },
  { hex: '#00ffff', name: 'Aqua' },
  { hex: '#7fffd4', name: 'Aquamarine' },
  { hex: '#f0ffff', name: 'Azure' },
  { hex: '#f5f5dc', name: 'Beige' },
  { hex: '#ffe4c4', name: 'Bisque' },
  { hex: '#000000', name: 'Black' },
  { hex: '#ffebcd', name: 'Blanched Almond' },
  { hex: '#0000ff', name: 'Blue' },
  { hex: '#8a2be2', name: 'Blu Violet' },
  { hex: '#a52a2a', name: 'Brown' },
  { hex: '#deb887', name: 'Burl Wood' },
  { hex: '#5f9ea0', name: 'Cade Blue' },
  { hex: '#7fff00', name: 'Chartreuse' },
  { hex: '#d2691e', name: 'Chocolate' },
  { hex: '#ff7f50', name: 'Coral' },
  { hex: '#6495ed', name: 'Cornflowe Blue' },
  { hex: '#fff8dc', name: 'Cornsilk' },
  { hex: '#dc143c', name: 'Crimson' },
  { hex: '#00ffff', name: 'Cyan' },
  { hex: '#00008b', name: 'Dar Blue' },
  { hex: '#008b8b', name: 'Dar Cyan' },
  { hex: '#b8860b', name: 'Dar Golde Rod' },
  { hex: '#a9a9a9', name: 'Dar Gray' },
  { hex: '#a9a9a9', name: 'Dar Grey' },
  { hex: '#006400', name: 'Dar Green' },
  { hex: '#bdb76b', name: 'Dar Khaki' },
  { hex: '#8b008b', name: 'Dar Magenta' },
  { hex: '#556b2f', name: 'Dark Oliv Green' },
  { hex: '#ff8c00', name: 'Dark Orange' },
  { hex: '#9932cc', name: 'Dark Orchid' },
  { hex: '#8b0000', name: 'Dar Red' },
  { hex: '#e9967a', name: 'Dar Salmon' },
  { hex: '#8fbc8f', name: 'DarkSe Green' },
  { hex: '#483d8b', name: 'Dar Slat Blue' },
  { hex: '#2f4f4f', name: 'Dar Slat Gray' },
  { hex: '#2f4f4f', name: 'Dar Slat Grey' },
  { hex: '#00ced1', name: 'Dar Turquoise' },
  { hex: '#9400d3', name: 'Dar Violet' },
  { hex: '#ff1493', name: 'Dee Pink' },
  { hex: '#00bfff', name: 'DeepSk Blue' },
  { hex: '#696969', name: 'Di Gray' },
  { hex: '#696969', name: 'Di Grey' },
  { hex: '#1e90ff', name: 'Dodge Blue' },
  { hex: '#b22222', name: 'Fir Brick' },
  { hex: '#fffaf0', name: 'Flora White' },
  { hex: '#228b22', name: 'Fores Green' },
  { hex: '#ff00ff', name: 'Fuchsia' },
  { hex: '#dcdcdc', name: 'Gainsboro' },
  { hex: '#f8f8ff', name: 'Ghos White' },
  { hex: '#ffd700', name: 'Gold' },
  { hex: '#daa520', name: 'Golde Rod' },
  { hex: '#808080', name: 'Gray' },
  { hex: '#808080', name: 'Grey' },
  { hex: '#008000', name: 'Green' },
  { hex: '#adff2f', name: 'Gree Yellow' },
  { hex: '#f0fff0', name: 'Honey Dew' },
  { hex: '#ff69b4', name: 'Ho Pink' },
  { hex: '#cd5c5c', name: 'India Red' },
  { hex: '#4b0082', name: 'Indigo' },
  { hex: '#fffff0', name: 'Ivory' },
  { hex: '#f0e68c', name: 'Khaki' },
  { hex: '#e6e6fa', name: 'Lavender' },
  { hex: '#fff0f5', name: 'LavenderBlush' },
  { hex: '#7cfc00', name: 'Law Green' },
  { hex: '#fffacd', name: 'Lemo Chiffon' },
  { hex: '#add8e6', name: 'Ligh Blue' },
  { hex: '#f08080', name: 'LightCoral' },
  { hex: '#e0ffff', name: 'Ligh Cyan' },
  { hex: '#fafad2', name: 'Ligh Golden Rod Yellow' },
  { hex: '#d3d3d3', name: 'Ligh Gray' },
  { hex: '#d3d3d3', name: 'Ligh Grey' },
  { hex: '#90ee90', name: 'Ligh Green' },
  { hex: '#ffb6c1', name: 'Ligh Pink' },
  { hex: '#ffa07a', name: 'Ligh Salmon' },
  { hex: '#20b2aa', name: 'LightSe Green' },
  { hex: '#87cefa', name: 'LightSk Blue' },
  { hex: '#778899', name: 'Ligh Slat Gray' },
  { hex: '#778899', name: 'Ligh Slat Grey' },
  { hex: '#b0c4de', name: 'LightStee Blue' },
  { hex: '#ffffe0', name: 'Ligh Yellow' },
  { hex: '#00ff00', name: 'Lime' },
  { hex: '#32cd32', name: 'Lim Green' },
  { hex: '#faf0e6', name: 'Linen' },
  { hex: '#ff00ff', name: 'Magenta' },
  { hex: '#800000', name: 'Maroon' },
  { hex: '#66cdaa', name: 'Medium Aqua Marine' },
  { hex: '#0000cd', name: 'Mediu Blue' },
  { hex: '#ba55d3', name: 'Medium Orchid' },
  { hex: '#9370db', name: 'Medium Purple' },
  { hex: '#3cb371', name: 'Medium Sea Green' },
  { hex: '#7b68ee', name: 'Mediu Slat Blue' },
  { hex: '#00fa9a', name: 'Medium Sprin Green' },
  { hex: '#48d1cc', name: 'Mediu Turquoise' },
  { hex: '#c71585', name: 'Medium Violet Red' },
  { hex: '#191970', name: 'Midnight Blue' },
  { hex: '#f5fffa', name: 'Mint Cream' },
  { hex: '#ffe4e1', name: 'Misty Rose' },
  { hex: '#ffe4b5', name: 'Moccasin' },
  { hex: '#ffdead', name: 'Navajo White' },
  { hex: '#000080', name: 'Navy' },
  { hex: '#fdf5e6', name: 'Old Lace' },
  { hex: '#808000', name: 'Olive' },
  { hex: '#6b8e23', name: 'Olive Drab' },
  { hex: '#ffa500', name: 'Orange' },
  { hex: '#ff4500', name: 'Orange Red' },
  { hex: '#da70d6', name: 'Orchid' },
  { hex: '#eee8aa', name: 'Pale Golden Rod' },
  { hex: '#98fb98', name: 'Pale Green' },
  { hex: '#afeeee', name: 'Pale Turquoise' },
  { hex: '#db7093', name: 'Pale Violet Red' },
  { hex: '#ffefd5', name: 'Papaya Whip' },
  { hex: '#ffdab9', name: 'Peach Puff' },
  { hex: '#cd853f', name: 'Peru' },
  { hex: '#ffc0cb', name: 'Pink' },
  { hex: '#dda0dd', name: 'Plum' },
  { hex: '#b0e0e6', name: 'Powder Blue' },
  { hex: '#800080', name: 'Purple' },
  { hex: '#663399', name: 'Rebecca Purple' },
  { hex: '#ff0000', name: 'Red' },
  { hex: '#bc8f8f', name: 'Rosy Brown' },
  { hex: '#4169e1', name: 'Royal Blue' },
  { hex: '#8b4513', name: 'Saddle Brown' },
  { hex: '#fa8072', name: 'Salmon' },
  { hex: '#f4a460', name: 'Sandy Brown' },
  { hex: '#2e8b57', name: 'Sea Green' },
  { hex: '#fff5ee', name: 'Sea Shell' },
  { hex: '#a0522d', name: 'Sienna' },
  { hex: '#c0c0c0', name: 'Silver' },
  { hex: '#87ceeb', name: 'Sk Blue' },
  { hex: '#6a5acd', name: 'Slat Blue' },
  { hex: '#708090', name: 'Slat Gray' },
  { hex: '#708090', name: 'Slat Grey' },
  { hex: '#fffafa', name: 'Snow' },
  { hex: '#00ff7f', name: 'Sprin Green' },
  { hex: '#4682b4', name: 'Stee Blue' },
  { hex: '#d2b48c', name: 'Tan' },
  { hex: '#008080', name: 'Teal' },
  { hex: '#d8bfd8', name: 'Thistle' },
  { hex: '#ff6347', name: 'Tomato' },
  { hex: '#40e0d0', name: 'Turquoise' },
  { hex: '#ee82ee', name: 'Violet' },
  { hex: '#f5deb3', name: 'Wheat' },
  { hex: '#ffffff', name: 'White' },
  { hex: '#f5f5f5', name: 'Whit Smoke' },
  { hex: '#ffff00', name: 'Yellow' },
  { hex: '#9acd32', name: 'Yello Green' }
];


export const colors = data.map(({ hex, name }) => {
  // calculate rgb
  let r = parseInt(hex.slice(1, 3), 16);
  let g = parseInt(hex.slice(3, 5), 16);
  let b = parseInt(hex.slice(5, 7), 16);
  const rgb = `rgb(${r}, ${g}, ${b})`;
  // calculate hsl
  r /= 255;
  g /= 255;
  b /= 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;
  if (max > min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = (g - b) / d + (g < b ? 6 : 0); break;
      case g: h = (b - r) / d + 2; break;
      case b: h = (r - g) / d + 4; break;
    }
    h /= 6;
  }
  const hsl = `hsl(${Math.round(h * 360)}, ${Math.round(s * 100)}%, ${Math.round(l * 100)}%)`;
  return {
    name,
    hex,
    rgb,
    hsl
  };
});
